project:
  type: book
  output-dir: docs

book:
  title: "Fluid2"
  author:
    - "M. T. Khater"
    - "S. I. Hassan"
  date: "11/11/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

